Add new precompile named crossChainCall to support external-call-module
QuarkChain/go-ethereum pull request #101
Opened 2022-09-27 02:03 UTC by cyl19970726

2022-09-27 02:23 UTC, cyl19970726 commented
1. Add a new precompile contract named crossChainCall at core/vm/contracts.go
2. Add unit test at test/state_test.go (the uint test at this file location is to avoid circular references)

2022-09-28 17:56 UTC, qizhou requested changes

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +	if len(input) != 164 {
Rename 164 to a constant?

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +		data_len= 32 + (32 - maxDataLen % 32) + maxDatalen
I think this equation is incorrect if `maxDataLen = n * 32`?  I guess it should be `32 + roundUp(32, maxDataLen)`.  BTW: where is the first 32 coming from?

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +		return nil, 0, fmt.Errorf("invalid length of input")
I think we should put all errors into evm execution errors list in errors.go?

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +			Idx := env.evm.Interpreter().CallResultIdx()
nit: Idx => idx

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +	//Data []byte `json:"data" gencodec:"required"`
remove this line?

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +	}
I guess you could just call `data = getData(log.Data, 0, maxDataLen)` directly

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +		topics_len = 3 *32 + 32 * 4(consider that the max number of topics is 4)
```suggestion
		topics_len = 3 * 32 + 4 * 32 (consider that the max number of topics is 4)
```

2022-09-28 17:56 UTC, qizhou commented on core/vm/contracts.go
> +				actualGasUsed := callres.GasCost(params.ExternalCallByteGasCost)
This seems to call ABIPack() twice.  Why not just use `actualGasUsed = len(resultValuePack) * params.ExternalCallByteGasCost` directly?

Further, I think a major issue here is that `maxDataLen` definitions in different functions are conflicting:

- In RequiredGas(), it is used to cap the returned log data
- here, the actual size of ABI packed data may be greater than `maxDataLen`

As a result, looks like it is possible that the `actualUsedGas` is greater than `requiredGas`?

2022-10-08 06:39 UTC, cyl19970726 commented on core/vm/contracts.go
> +		data_len= 32 + (32 - maxDataLen % 32) + maxDatalen
yeah, the correct formula is :
```
if maxDataLen % 32 != 0 
			data_len= 32 + (32 - maxDataLen % 32) + maxDatalen
if maxDataLen %32 == 0 
			data_len= 32 + maxDatalen
```

And, the first 32 is the length of data.

2022-10-08 07:29 UTC, cyl19970726 commented on core/vm/contracts.go
> +				actualGasUsed := callres.GasCost(params.ExternalCallByteGasCost)
Question: This seems to call ABIPack() twice?
ABIPack() is actually only executed once. The callres is not the result of ABIPack(address,topics,data) but a structure named GetLogByTxHash containing (address,topics,data),and ABIPack(address, topics, data) is actually executed on line 1335. This is also the reason why GasCost() is used to calculate gas。

2022-10-08 07:30 UTC, cyl19970726 commented on core/vm/contracts.go
> +				actualGasUsed := callres.GasCost(params.ExternalCallByteGasCost)
Question: This seems to call ABIPack() twice?
`ABIPack()`  is actually only executed once. The callres is not the result of `ABIPack(address,topics,data)`  but a structure named `GetLogByTxHash`c containing `(address,topics,data)`, and `ABIPack(address, topics, data)` is actually executed on line 1335(`resultValuePack, err := callres.ABIPack()`). This is also the reason why `GasCost()` is used to calculate gas.

2022-10-08 07:52 UTC, cyl19970726 commented on core/vm/contracts.go
> +				actualGasUsed := callres.GasCost(params.ExternalCallByteGasCost)
Response to conflicting gas calculations in `ResuireGas()` and `Runwith()`：

`RequireGas` calculates gasCost according to the result of `MaxLength(ABIPack(address,topics,data))` instead of MaxLength(address,topics,data).

This is the resason why the formula of  `topics_len = 3 *32 + 32 * 4`] includes `3 * 32` which is the prefix of `ABIPack(topics[0],topics[1],topics[2],topics[3])`

This is also the reason why the formula of  `data_len` includes the first 32.

2022-10-19 03:14 UTC, blockchaindevsh commented on core/vm/contracts.go
> +	return nil, nil
Prefer to return an explicit error since it's not supposed to be called

2022-10-19 03:14 UTC, blockchaindevsh commented on core/vm/evm.go
> +func (evm *EVM) SetCrossChainCallResultsByUncles(uncles []*types.Header, tx *types.Transaction) {
seems this func is never called?

2022-10-19 03:14 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		if client == nil {
when `ExternalCallClient` is nil, I think it's better to just return an explicit error? For a call to `crossChainCall` to finally succeed, at least quorum of validators should have set `ExternalCallClient`. In this regard I think `VerifyCrossChainCall` is not needed.

2022-10-19 03:17 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		return 0
When something abnormal happens, I think it's better to charge a high fee instead of free?

2022-10-19 09:01 UTC, cyl19970726 commented on core/vm/contracts.go
> +			callres, expErr, unexpErr := GetExternalLog(ctx, env, chainId, txHash, logIdx, maxDataLen, confirms)
In the design of ExternalCall, the application has the ability to customize confirms to meet different usage scenarios.

2022-10-19 10:04 UTC, cyl19970726 commented on core/vm/contracts.go
> +		return 0
Do I need to modify `crossChainCall.RunWith()` synchronously?

2022-10-19 14:04 UTC, blockchaindevsh commented on core/vm/contracts.go
> +			callres, expErr, unexpErr := GetExternalLog(ctx, env, chainId, txHash, logIdx, maxDataLen, confirms)
If the confirm is lower than some minimum threshold, I can only imagine asset loss in that case. The lower bound should be ensured, but the user can specify a higher confirm if he wants.

2022-10-19 14:08 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		return 0
I mean, the idea is that if the pattern is obviously an attack, you should charge high price instead of free. I'm not detailing exact places to modify here.

2022-10-20 13:47 UTC, cyl19970726 commented on core/vm/evm.go
> +func (evm *EVM) SetCrossChainCallResultsByUncles(uncles []*types.Header, tx *types.Transaction) {
This func will be used at next external-call pr

2022-10-20 18:07 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		return 0
As long as it's no free, I think it's ok. Otherwise the hacker may cause DOS.

2022-10-21 09:08 UTC, cyl19970726 commented on core/vm/contracts.go
> +		if client == nil {
We need to allow ordinary nodes to still have the ability to execute external-call-tx, so as to ensure that the entire state-sync process will not be affected.

How ordinary nodes handle this kind of transaction？

- Node receives the block through p2p network when state-sync.
- Node fetchs all the external-call result from block.uncles.
- Node re-executes all transactions of the block.
  - The transaction set the external-call result at evm using `vmenv.SetCrossChainCallResultsByUncles(block.Uncles(), tx)` to provides the ability to execute external-call transactions at `crossChainCall` precompile contract for normal node.
  - The crossChainCall fetchs the external-call result from `env.evm.Interpreter().CrossChainCallResults()[Idx]` when the client is nil to continue to execute the transaction.

2022-10-21 12:26 UTC, cyl19970726 commented on core/vm/contracts.go
> +		if client == nil {
Add new flag IsStateSync to deal with this case: https://github.com/QuarkChain/go-ethereum/pull/101/commits/52dde717fd6638bf3586f04f56992046beed1fe3

2022-10-23 14:22 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		if client == nil {
Is `SetCrossChainCallResultsByUncles` necessary? What about just passing the additional Uncles etc and do calculations inside the precompile ?

2022-10-24 01:50 UTC, cyl19970726 commented on core/vm/evm.go
> +func (evm *EVM) SetCrossChainCallResultsByUncles(uncles []*types.Header, tx *types.Transaction) {
The function has been removed.

2022-10-24 01:50 UTC, cyl19970726 commented on core/vm/contracts.go
> +		if client == nil {
The function named `SetCrossChainCallResultsByUncles()` has been removed.

2022-10-25 04:23 UTC, blockchaindevsh commented on core/vm/contracts.go
> +		suppliedGas += gasCost - actualGasUsed
need to handle overflow?

2022-10-25 04:24 UTC, blockchaindevsh commented on core/vm/contracts.go
> +	if env.evm.ChainConfig().ExternalCall.EnableBlockNumber == nil {
maybe IsStateSync should have higher priority?

2022-10-25 04:50 UTC, blockchaindevsh commented on core/vm/contracts.go
> +			idx := env.evm.Interpreter().CallResultIdx()
how is `idx` decided?

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +			if confirms < env.evm.ChainConfig().ExternalCall.ConfirmsNether {
ConfirmsNether => MinimumConfirms

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +				env.evm.setCrossChainCallUnExpectErr(unexpErr)
UnExpect => Unexpect

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +		maxDataLen = maxDataLen + (32 - maxDataLen%32)
Check if maxDataLen is overflowed?

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +	callResultGas += maxDataLen * params.ExternalCallByteGasCost
Check if callResultGas is not overflowed?

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +	gasUsed := callResultGas + inputGas + params.ExternalCallGas
Check if the summation is not overflowed?

2022-10-26 22:40 UTC, qizhou commented on core/vm/interpreter.go
> +	IsStateSync        bool               // Define the execution environment of crossChainCall precompile contract
I am not sure IsStateSync is easy to understand - state sync (snap sync) does not touch the EVM.

I think a better word is "replayExternalCalls"?

2022-10-26 22:40 UTC, qizhou commented on core/vm/evm.go
> +func (evm *EVM) EnableExternalCall() bool {
EnableExternalCall() => IsExternalCallEnabled() (Enable xxxx may be mis-understood as enable something (set something to true)

2022-10-26 22:40 UTC, qizhou commented on core/vm/contracts.go
> +	if env.evm.Context.BlockNumber.Cmp(env.evm.ChainConfig().ExternalCall.EnableBlockNumber) == -1 {
These two if's can be replaced by `evm.IsExternalCallEnabled`?

2022-10-27 03:28 UTC, cyl19970726 commented on core/vm/contracts.go
> +		suppliedGas += gasCost - actualGasUsed
I add a  mechanism to guarantee that actualGas is less than GasCost while to avoid overflow case because  `suppliedGas -= gasCost` has executed at line 191

2022-10-27 03:41 UTC, cyl19970726 commented on core/vm/contracts.go
> +			if confirms < env.evm.ChainConfig().ExternalCall.ConfirmsNether {
https://github.com/QuarkChain/go-ethereum/pull/101/commits/9c9e0f2325d05ed0b6f8968596a379e0e5cbf1d5

2022-10-27 03:42 UTC, cyl19970726 commented on core/vm/contracts.go
> +		suppliedGas += gasCost - actualGasUsed
https://github.com/QuarkChain/go-ethereum/pull/101/commits/9c9e0f2325d05ed0b6f8968596a379e0e5cbf1d5

2022-10-27 04:12 UTC, cyl19970726 commented on core/vm/interpreter.go
> +	IsStateSync        bool               // Define the execution environment of crossChainCall precompile contract
Is `IsRelayExternalCallsEnabled`  better than `replayExternalCalls` ?

2022-10-27 04:16 UTC, cyl19970726 commented on core/vm/contracts.go
> +	if env.evm.ChainConfig().ExternalCall.EnableBlockNumber == nil {
I think the process of judging the external-call module whether is active should higher than IsStateSync  because the crossChainCall precompile contract should not be invokled if external-call module is not active .

2022-10-27 04:17 UTC, qizhou commented on core/vm/interpreter.go
> +	IsStateSync        bool               // Define the execution environment of crossChainCall precompile contract
Or `IsReplayingExternalCalls` as replay is a verb

2022-10-31 02:09 UTC, cyl19970726 commented on core/vm/contracts.go
> +	callResultGas += maxDataLen * params.ExternalCallByteGasCost
I think you mean "Check if callResultGas is overflowed?"

2023-01-03 01:23 UTC, cyl19970726 commented on core/vm/evm.go
> +	if evm.ExternalCallClient() == nil && evm.IsExternalCallEnabled() && len(result) != 0 {
SetCrossChainCallResult will occur when the EVM is initialized. 
In some cases it is not necessary to set CrossChainCallResult, so it should not return an error.

2023-01-09 15:15 UTC, cyl19970726 commented on core/vm/contracts.go
> +	if bytes.Equal(input[0:4], getLogByTxHashId) {
the crossChain 'eth_call' is simaliar to the getLogByTxHash and most of the code can be reused When we support cross-chain 'eth_call'(in my view I think RequireGas() can also be reused)

2023-01-10 05:51 UTC, cyl19970726 commented on core/vm/contracts.go
> +			idx := env.evm.Interpreter().CallResultIdx()
IDX indicates which cross-chain call result obtained by the transaction during EVM execution. (a transaction may contain multiple cross-chain call requests)
It means that the result of the first call corresponds to idx 1, and the result of the second call corresponds to idx 2

2023-02-28 05:49 UTC, qizhou commented
Need to rebase before merge?

2023-03-07 02:10 UTC, qizhou approved these changes

2023-03-09 02:47 UTC, merged